apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Admiralissimus/IBA-DevOps-Practicum-Diplom2.git
    targetRevision: HEAD
    path: monitoring
  destination: 
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true