apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: prometheus_stack
spec:
  project: default
  source:
    chart: kube-prometheus-stack
    repoURL: 'https://github.com/prometheus-community/helm-charts'
    targetRevision: HEAD
  destination:
    namespace: prometheus_stack
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true