apiVersion: v1
kind: Service
metadata:
  name: rps-app-lb
  namespace: rps-app
spec:
  selector:
    app: rps-app
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    #nodePort: 30080
  type: LoadBalancer
  
