apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: charts/prometheus
    repoURL: 'https://github.com/prometheus-community/helm-charts'
    targetRevision: 2822d8f
    helm:
      parameters:
        - name: server.persistentVolume.enabled
          value: 'false'
        - name: alertmanager.enabled
          value: 'false'
  destination:
    namespace: monitoring
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
